sudo: true
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libgmp-dev

script:
  - make -j3
  - make test_ci
  - make test_go
  - env LD_LIBRARY_PATH=../mcl/lib bin/bls_c384_test.exe
  - make clean && make -C ../mcl clean
  - make -j3 MCL_USE_OPENSSL=0
  - make test_ci DISABLE_THREAD_TEST=1 MCL_USE_OPENSSL=0
